version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "12:00"
    timezone: Europe/Athens
  open-pull-requests-limit: 10
  reviewers:
  - XhmikosR
  labels:
  - dependencies
  - v5
  versioning-strategy: increase
  ignore:
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - ">= 8.a, < 9"
  rebase-strategy: disabled
