fail_on_violations: true

<<<<<<< HEAD
stylelint:
  config_file: build/.stylelintrc
  enabled: true
  ignore_file: .houndignore

eslint:
  config_file: js/.eslintrc.json
  ignore_file: .houndignore

scss:
  enabled: false

jshint:
  enabled: false

ruby:
  enabled: false
=======
scss:
  enabled: false

javascript:
  enabled: true
  config_file: js/.jshintrc

jscs:
  enabled: true
  config_file: js/.jscsrc
>>>>>>> upstream/master
