language: node_js
node_js:
  - 0.8
before_script:
  - npm install -g grunt-cli
env:
  global:
  - secure: bIqcPK0Rtlv3e8rM6SPDC780yXxGj8AWHxPgbRXz2Os1bRdR6YVJtHXGpDmviVYBwWto4Zevljo7puUUnZ9IXPB+whckSIjut5sUqgXmWy1sROE98oPYi5H46ddH2zjM85Uifr/deaFSDJ5byrh+6+dHpMhgNL0duGmodpXfL6o=
  - secure: YE0/FYpsuDvCYmxRtOvdSpx6XNnC19rdxWGuAJXOHH6x0sB6HwsoFVH2EYa8WXNjri+A+8bH8AZX1vHoIY8gKZAARrLn9kN/sVpcT/Z7jpPTLVIyg9LD59wdCWh5vwKYiriyDES5vTtqk3JOd6xy1ci+Nckl6t9Khh6mJ5V4A98=
