sudo: required
dist: trusty
<<<<<<< HEAD
addons:
  chrome: stable
=======
>>>>>>> cee8e8653dc009b5d86af4a8e2ad3a5e0688ca4c
language: node_js
git:
  depth: 3
node_js:
  - "6"
<<<<<<< HEAD
  - "8"
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install
script:
  - npm test
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run check-broken-links; fi
after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run coveralls; fi
stages:
  - test
  - name: browser
    if: type = push
jobs:
  include:
    - stage: browser
      node_js: 8
      script: if ! git log --format=%B --no-merges -n 1 | grep '\[skip browser\]'; then npm run js-test-cloud; fi
=======
before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install 2.2
  - rvm use 2.2 --fuzzy
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip sauce\]'; export TWBS_DO_SAUCE=$?; true
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then export TWBS_DO_VALIDATOR=0; fi
install:
  - bundle install --deployment --jobs=1
  - cp grunt/npm-shrinkwrap.json ./
  - npm install
# Undo `_JAVA_OPTIONS` environment variable;
# see https://github.com/travis-ci/travis-ci/issues/8408
before_script:
  - _JAVA_OPTIONS=
>>>>>>> cee8e8653dc009b5d86af4a8e2ad3a5e0688ca4c
cache:
  directories:
    - node_modules
    - vendor/bundle
