name: CI
on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    - name: Test
      if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
      run: echo success!
